esphome:
  name: test-sfm-v17
  friendly_name: test-sfm-v17

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  # level: verbose

# Enable Home Assistant API
api:
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

time:
  - platform: homeassistant

select:
  - platform: template
    id: color_start
    name: "Color start"
    optimistic: true
    options:
      - "yellow"
      - "purple"
      - "red"
      - "cyan"
      - "green"
      - "blue"
      - "off"
    initial_option: "yellow"
  - platform: template
    id: color_end
    name: "Color end"
    optimistic: true
    options:
      - "yellow"
      - "purple"
      - "red"
      - "cyan"
      - "green"
      - "blue"
      - "off"
    initial_option: "off"

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
  - platform: factory_reset
    name: Reset
    entity_category: diagnostic
  - platform: template
    name: Scan # manual Scan if IRQ pin disabled
    on_press:
      then:
        - lambda: |-
            id(sfm_id).start_scan();
  - platform: template
    name: Register
    on_press:
      then:
        - lambda: |-
            id(sfm_id).start_register();
  - platform: template
    name: "Yellow Green"
    on_press:
      then:
        - sfm_v1_7.set_color:
            start: red
            end: green
  - platform: template
    name: "Color from selects"
    on_press:
      then:
        - lambda: |-
            auto start = static_cast<sfm_v1_7::SFM_Color>(1 + id(color_start).active_index().value());
            auto end = static_cast<sfm_v1_7::SFM_Color>(1 + id(color_end).active_index().value());
            id(sfm_id).set_color(start, end);

uart:
  id: uart_for_sfm
  tx_pin: 26
  rx_pin: 27
  baud_rate: 115200
  # debug:
  #   direction: BOTH
  #   sequence:
  #      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

sfm_v1_7:
  id: sfm_id
  uart_id: uart_for_sfm
  vcc_pin: 2
  # vcc_always_on: true
  irq_pin: 15
  # dir_pin: 20
  error:
    name: Error

external_components:
  - source: github://dvb6666/esphome-components
    refresh: 1sec
