esphome:
  name: test-climate-ir-sams
  friendly_name: test-climate-ir-sams

esp8266:
  board: esp01_1m

logger:
api:
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

external_components:
  - source: github://dvb6666/esphome-components
    refresh: 1sec
climate:
  - platform: climate_ir_samsung
    name: Livingroom AC
    ir_led: 14
    sensor: scd40_temperature
    # default_temperature: 25.0°C
    # min_temperature: 16.0°C
    # max_temperature: 30.0°C

# Test fake temperature Sensor taking value from Number
number:
  - platform: template
    name: "Fake Temperature"
    optimistic: true
    initial_value: 20
    min_value: 16
    max_value: 30
    step: 1
    on_value:
      - sensor.template.publish:
          id: scd40_temperature
          state: !lambda 'return x;'
sensor:
  - platform: template
    id: scd40_temperature
    name: "Fake Temperature Sensor"
    device_class: temperature
    update_interval: never
